import c1_img from "./course_img1.jpg";
import c2_img from "./course_img2.jpg";
import c3_img from "./course_img3.jpg";
import c4_img from "./course_img4.jpg";
import c5_img from "./course_img5.jpg";
import c6_img from "./course_img6.jpg";
import c7_img from "./course_img07.jpg";
import c8_img from "./course_img08.jpg";
import c9_img from "./course_img09.jpg";
import c10_img from "./course_img10.jpg";
import c11_img from "./course_img11.jpg";
import c12_img from "./course_img12.jpg";
import c13_img from "./course_img13.jpg";
import c14_img from "./course_img14.jpg";
import c15_img from "./course_img15.jpg";
import c16_img from "./course_img16.jpg";
import c17_img from "./course_img17.jpg";
import c18_img from "./course_img18.jpg";
import c19_img from "./course_img19.jpg";
import c20_img from "./course_img20.jpg";
import c21_img from "./course_img21.jpg";
import c22_img from "./course_img22.jpg";
import c23_img from "./course_img23.jpg";
import c24_img from "./course_img24.jpg";
import c25_img from "./course_img25.jpg";
import c26_img from "./course_img26.jpg";
import c27_img from "./course_img27.jpg";
import c28_img from "./course_img28.jpg";
import c29_img from "./course_img29.jpg";

const courses = [
  {
    id: 1,
    name: "Machine Learning In Python Environment",
    image: c1_img,
    tags: [
      "machine_learning",
      "introduction",
      "beginner",
      "artificial_intelligence",
      "python",
      "scikit-learn",
    ],
    pricing: "free",
    certificate_included: true,
    provider: "alison.com",
    url: "https://alison.com/course/machine-learning-in-python-environment",
  },
  {
    id: 2,
    name: "Introduction to Deep Learning with TensorFlow",
    image: c2_img,
    tags: ["deep_learning", "tensorflow", "beginner", "ai", "python"],
    pricing: "free",
    certificate_included: true,
    provider: "coursera.org",
    url: "https://coursera.org/learn/deep-learning-tensorflow",
  },
  {
    id: 3,
    name: "Data Science Essentials in Python",
    image: c3_img,
    tags: [
      "data_science",
      "python",
      "pandas",
      "numpy",
      "beginner",
      "statistics",
    ],
    pricing: "paid",
    certificate_included: true,
    provider: "udemy.com",
    url: "https://udemy.com/course/data-science-essentials",
  },
  {
    id: 4,
    name: "Artificial Intelligence for Everyone",
    image: c4_img,
    tags: ["ai", "non-technical", "introduction", "machine_learning"],
    pricing: "free",
    certificate_included: false,
    provider: "edx.org",
    url: "https://edx.org/course/artificial-intelligence-for-everyone",
  },
  {
    id: 5,
    name: "Full Stack Web Development Bootcamp",
    image: c5_img,
    tags: [
      "web_development",
      "full_stack",
      "html",
      "css",
      "javascript",
      "react",
      "node.js",
    ],
    pricing: "paid",
    certificate_included: true,
    provider: "codecademy.com",
    url: "https://codecademy.com/learn/full-stack-web-development",
  },
  {
    id: 6,
    name: "Introduction to Cloud Computing",
    image: c6_img,
    tags: ["cloud_computing", "beginner", "aws", "azure", "google_cloud"],
    pricing: "free",
    certificate_included: true,
    provider: "simplilearn.com",
    url: "https://simplilearn.com/introduction-to-cloud-computing",
  },
  {
    id: 7,
    name: "Cybersecurity Basics",
    image: c7_img,
    tags: ["cybersecurity", "beginner", "network_security", "ethical_hacking"],
    pricing: "free",
    certificate_included: false,
    provider: "futurelearn.com",
    url: "https://futurelearn.com/courses/cybersecurity-basics",
  },
  {
    id: 8,
    name: "Introduction to DevOps",
    image: c8_img,
    tags: ["devops", "ci_cd", "automation", "docker", "kubernetes"],
    pricing: "paid",
    certificate_included: true,
    provider: "pluralsight.com",
    url: "https://pluralsight.com/courses/introduction-to-devops",
  },
  {
    id: 9,
    name: "Programming in C++",
    image: c9_img,
    tags: ["c++", "programming", "beginner", "oop", "data_structures"],
    pricing: "free",
    certificate_included: false,
    provider: "codecademy.com",
    url: "https://codecademy.com/learn/programming-in-cpp",
  },
  {
    id: 10,
    name: "Digital Marketing Fundamentals",
    image: c10_img,
    tags: [
      "digital_marketing",
      "seo",
      "social_media",
      "content_marketing",
      "beginner",
    ],
    pricing: "paid",
    certificate_included: true,
    provider: "hubspot.com",
    url: "https://hubspot.com/learn/digital-marketing",
  },
  {
    id: 11,
    name: "Python for Data Analysis",
    image: c11_img,
    tags: ["python", "data_analysis", "pandas", "numpy", "beginner"],
    pricing: "free",
    certificate_included: true,
    provider: "kaggle.com",
    url: "https://kaggle.com/learn/python",
  },
  {
    id: 12,
    name: "Blockchain Basics",
    image: c12_img,
    tags: [
      "blockchain",
      "cryptocurrency",
      "beginner",
      "technology",
      "ethereum",
    ],
    pricing: "free",
    certificate_included: false,
    provider: "ibm.com",
    url: "https://ibm.com/blockchain/basics",
  },
  {
    id: 13,
    name: "Mobile App Development with Flutter",
    image: c13_img,
    tags: ["mobile_app", "flutter", "dart", "beginner", "cross_platform"],
    pricing: "paid",
    certificate_included: true,
    provider: "udemy.com",
    url: "https://udemy.com/course/flutter-development",
  },
  {
    id: 14,
    name: "Kotlin for Android Developers",
    image: c14_img,
    tags: ["kotlin", "android", "app_development", "beginner", "programming"],
    pricing: "free",
    certificate_included: true,
    provider: "developer.android.com",
    url: "https://developer.android.com/kotlin",
  },
  {
    id: 15,
    name: "Big Data and Hadoop",
    image: c15_img,
    tags: ["big_data", "hadoop", "analytics", "data_engineering"],
    pricing: "paid",
    certificate_included: true,
    provider: "edureka.co",
    url: "https://edureka.co/big-data-and-hadoop",
  },
  {
    id: 16,
    name: "AI in Healthcare",
    image: c16_img,
    tags: ["ai", "healthcare", "technology", "beginner", "machine_learning"],
    pricing: "free",
    certificate_included: false,
    provider: "stanford.edu",
    url: "https://stanford.edu/courses/ai-in-healthcare",
  },
  {
    id: 17,
    name: "React for Beginners",
    image: c17_img,
    tags: ["react", "javascript", "frontend", "web_development"],
    pricing: "free",
    certificate_included: true,
    provider: "scrimba.com",
    url: "https://scrimba.com/learn/react",
  },
  {
    id: 18,
    name: "Docker Essentials",
    image: c18_img,
    tags: ["docker", "containers", "devops", "beginner"],
    pricing: "paid",
    certificate_included: true,
    provider: "linuxfoundation.org",
    url: "https://linuxfoundation.org/learn/docker-essentials",
  },
  {
    id: 19,
    name: "SQL for Data Analysis",
    image: c19_img,
    tags: ["sql", "data_analysis", "databases", "beginner"],
    pricing: "free",
    certificate_included: true,
    provider: "dataquest.io",
    url: "https://dataquest.io/sql-for-data-analysis",
  },
  {
    id: 20,
    name: "Game Development with Unity",
    image: c20_img,
    tags: ["game_development", "unity", "c#", "beginner"],
    pricing: "paid",
    certificate_included: true,
    provider: "learn.unity.com",
    url: "https://learn.unity.com",
  },
  {
    id: 21,
    name: "Introduction to Kubernetes",
    image: c21_img,
    tags: ["kubernetes", "devops", "orchestration", "cloud"],
    pricing: "free",
    certificate_included: true,
    provider: "cncf.io",
    url: "https://cncf.io/kubernetes",
  },
  {
    id: 22,
    name: "Building APIs with Node.js",
    image: c22_img,
    tags: ["node.js", "api", "backend", "web_development"],
    pricing: "paid",
    certificate_included: true,
    provider: "udemy.com",
    url: "https://udemy.com/course/node-api-development",
  },
  {
    id: 23,
    name: "UI/UX Design for Beginners",
    image: c23_img,
    tags: ["ui_ux", "design", "figma", "adobe_xd", "beginner"],
    pricing: "free",
    certificate_included: false,
    provider: "coursera.org",
    url: "https://coursera.org/learn/ui-ux-design",
  },
  {
    id: 24,
    name: "Java Programming Masterclass",
    image: c24_img,
    tags: ["java", "programming", "beginner", "oop"],
    pricing: "paid",
    certificate_included: true,
    provider: "udemy.com",
    url: "https://udemy.com/course/java-programming-masterclass",
  },
  {
    id: 25,
    name: "Introduction to Networking",
    image: c25_img,
    tags: ["networking", "ccna", "beginner", "computer_networks"],
    pricing: "free",
    certificate_included: true,
    provider: "cisco.com",
    url: "https://cisco.com/introduction-to-networking",
  },
  {
    id: 26,
    name: "Ethical Hacking Essentials",
    image: c26_img,
    tags: [
      "ethical_hacking",
      "cybersecurity",
      "penetration_testing",
      "beginner",
    ],
    pricing: "paid",
    certificate_included: true,
    provider: "ceh.com",
    url: "https://ceh.com/ethical-hacking",
  },
  {
    id: 27,
    name: "Advanced Excel Techniques",
    image: c27_img,
    tags: ["excel", "data_analysis", "spreadsheets", "advanced"],
    pricing: "free",
    certificate_included: true,
    provider: "microsoft.com",
    url: "https://microsoft.com/advanced-excel",
  },
  {
    id: 28,
    name: "Angular for Web Development",
    image: c28_img,
    tags: ["angular", "javascript", "frontend", "web_development"],
    pricing: "paid",
    certificate_included: true,
    provider: "pluralsight.com",
    url: "https://pluralsight.com/courses/angular",
  },
  {
    id: 29,
    name: "Linux for Beginners",
    image: c29_img,
    tags: ["linux", "command_line", "operating_system", "beginner"],
    pricing: "free",
    certificate_included: true,
    provider: "linuxfoundation.org",
    url: "https://linuxfoundation.org/learn/linux",
  },
];
